apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhdh-test 
  janus-idp.io/tekton: rhdh-test
  backstage.io/kubernetes-id: rhdh-test
  backstage.io/kubernetes-namespace: rhdh-test 
  app.kubernetes.io/part-of: rhdh-test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  